#!/bin/bash
# Test installation and operation modes.

cd $(npm prefix)
source ./test/test_helpers

header "Running tests"

# Cleaning previous run
TEST_PROJECT=test/sample_project
rm -rf $TEST_PROJECT/node_modules $TEST_PROJECT/lib/no-tests.js $TEST_PROJECT/.git

# Installation...
PACKAGE_NAME=$(npm pack)
cd $TEST_PROJECT
npm install --save-dev ../../$PACKAGE_NAME || fail
log "✅  Install OK"

assert_file_exists .eslintrc.js
assert_file_exists .istanbul.yml
assert_file_exists .git/hooks/pre-push

# Operation
./node_modules/.bin/qc || fail
log "✅  QC OK"

assert_file_exists coverage/coverage.json

# Ensure all sources are covered
cp ../fixtures/no-tests.js ./lib/no-tests.js
assert_fails "Covers all sources" ./node_modules/.bin/qc

# Check lint of files.
log "Linting JS files in trussle-qc"
eslint bin/npm_test_command || fail
log "✅  Lint OK"

header "All tests passed!"
