#!/bin/bash
# Test installation and operation modes.

cd $(npm prefix)
source ./test/test_helpers

header "Running tests"

# Installation...
PACKAGE_NAME=$(npm pack)
cd test/sample_project
rm -rf node_modules
npm install --save-dev ../../$PACKAGE_NAME || fail
log "✅  Install OK"

assert_file_exists .eslintrc.js
assert_file_exists .istanbul.yml
assert_file_exists .git/hooks/pre-push

# Operation
./node_modules/.bin/qc || fail
log "✅  QC OK"

assert_file_exists coverage/coverage.json

# Check lint of files.
log "Linting JS files in trussle-qc"
eslint bin/npm_test_command || fail
log "✅  Lint OK"

header "All tests passed!"
